apiVersion: v1
kind: pod
metadata:
 name: tomcat-deployment
spec:
 selector:
  matchLabels:
   app: tomcat
 replicas: 1
 template:
  metadata:
   labels:
    app: tomcat
  spec:
   containers:
   - name: tomcat
     image: keerthi1987/docimg
     ports:
     - containerPort: 80
