apiVersion: apps/v1
kind: pod
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: devops-project
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: keerthi1987/docimg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
