apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: docker-deployment
spec:
  selector:
    matchLabels:
      app: devops-project
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: k8-devops-project
        image: keerthi1987/docimg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
