apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: firstwar
  name: firstkubwar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: firstwar
    spec:
      containers:
      - image: keerthi1987/docimg
        name: kubwar
        ports:
        - name: firstwar
          containerPort: 8081    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: firstwar
  name: firstwar
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: firstwar
